import express from "express";
import healthRoutes from "../modules/health/health.routes.js";
import authRoutes from "../modules/auth/auth.routes.js";
import userRouter from "../modules/users/user.routes.js";
import branchRoutes from "../modules/branches/branch.routes.js";
import customerRoutes from "../modules/customers/customer.routes.js";
import roleRoutes from "../modules/roles/role.routes.js";
import permissionRoutes from "../modules/permissions/permission.routes.js";
import loanRouter from "../modules/loan-products/loanProducts.routes.js";
import loanApplicationRouter from "../modules/loan-applications/loanApplications.routes.js";
import groupRoutes from "../modules/groups/groups.routes.js";
import collectionRoutes from "../modules/collections/collections.routes.js";
import loanRoutes from "../modules/loans/loans.routes.js";
import settingsRoutes from "../modules/settings/settings.routes.js";
import dashboardRoutes from "../modules/dashboard/dashboard.routes.js";
import reportRoutes from "../modules/reports/reports.routes.js";
import emiRoutes from "../modules/emi/emi.routes.js";
import customerPortalRoutes from "../modules/customer-portal/customerPortal.routes.js";
import taskRoutes from "../modules/tasks/tasks.routes.js";
import financeRoutes from "../modules/finance/finance.routes.js";

const router = express.Router();

router.use("/health", healthRoutes);
router.use("/auth", authRoutes);
router.use("/users", userRouter);
router.use("/branches", branchRoutes);
router.use("/customers", customerRoutes);
router.use("/roles", roleRoutes);
router.use("/permissions", permissionRoutes);
router.use("/loan-products", loanRouter);
router.use("/loan-application", loanApplicationRouter);
router.use("/loans", loanRoutes);
router.use("/groups", groupRoutes);
router.use("/collections", collectionRoutes);
router.use("/finance", financeRoutes);
router.use("/settings", settingsRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/reports", reportRoutes);
router.use("/emi", emiRoutes);
router.use("/customer", customerPortalRoutes);
router.use("/tasks", taskRoutes);

export default router;
